import { Boilerplate } from '../types';

export const boilerplates: Boilerplate[] = [
    {
        identifier: 'furniture-remix',
        name: 'Furniture Remix Run',
        baseline: 'Complete ecommerce using Remix Run',
        description: 'React, SSR, Ecommerce with basket & checkout, promotions, Payments (many), etc.',
        demo: 'https://furniture.superfast.store',
        blueprint: 'frntr-blueprint',
        git: 'https://github.com/CrystallizeAPI/furniture-remix',
    },
    {
        identifier: 'furniture-nextjs',
        name: 'Furniture Next.js',
        baseline: 'Complete ecommerce using Next.js',
        description: 'React, SSR, Ecommerce with basket & checkout, promotions, Payments (many), etc.',
        demo: 'https://furniture.superfast.store',
        blueprint: 'frntr-blueprint',
        git: 'https://github.com/CrystallizeAPI/furniture-nextjs',
    },
    {
        identifier: 'product-configurator',
        name: 'Next.js Product Configurator',
        baseline: 'Product Configurator boilerplate using Next.js',
        description: 'Ecommerce product configurator with basket & checkout.',
        demo: 'https://product-configurator.superfast.shop/',
        blueprint: 'product-configurator',
        git: 'https://github.com/CrystallizeAPI/product-configurator',
    },
    {
        identifier: 'dounut-remix',
        name: 'Dounut Remix',
        baseline: 'Ecommerce boilerplate using Remix',
        description: 'Minimal eCommerce boilerplate built using Remix, Tailwind, and Crystallize.',
        demo: 'https://dounot.milliseconds.live/',
        blueprint: 'dounot',
        git: 'https://github.com/CrystallizeAPI/product-storytelling-examples',
    },
    {
        identifier: 'dounut-svelte',
        name: 'Dounut Svelte',
        baseline: 'Ecommerce boilerplate using SvelteKit',
        description: 'Minimal eCommerce boilerplate built using SvelteKit, Houdini, Tailwind, and Crystallize.',
        demo: 'https://dounut-svelte.vercel.app/',
        blueprint: 'dounot',
        git: 'https://github.com/CrystallizeAPI/dounut-svelte',
    },
    {
        identifier: 'dounut-astro',
        name: 'Dounut Astro',
        baseline: 'Ecommerce boilerplate using Astro',
        description: 'Minimal eCommerce boilerplate built using Astro, Tailwind, and Crystallize.',
        demo: 'https://dounut-astro.vercel.app/',
        blueprint: 'dounot',
        git: 'https://github.com/CrystallizeAPI/dounut-astro',
    },
    {
        identifier: 'conference',
        name: 'Conference Next.js',
        baseline: 'Conference website using Next.js',
        description: 'Conference website boilerplate using Next.js and Crystallize.',
        demo: 'https://conference.superfast.shop/',
        blueprint: 'conference-boilerplate',
        git: 'https://github.com/CrystallizeAPI/conference-boilerplate',
    },
];
