const {
  CRYSTALLIZE_API_URL = '',
  MAGENTO_CONSUMER_KEY = '',
  MAGENTO_CONSUMER_SECRET = '',
  MAGENTO_ACCESS_TOKEN = '',
  MAGENTO_TOKEN_SECRET = '',
  MAGENTO_API_URL = '',
  MY_CRYSTALLIZE_SECRET_TOKEN_ID = '',
  MY_CRYSTALLIZE_SECRET_TOKEN = '',
  CRYSTALLIZE_TENANT_ID = '',
  CRYSTALLIZE_PRODUCT_SHAPE_ID = '',
  CRYSTALLIZE_FOLDER_SHAPE_ID = '',
  CRYSTALLIZE_ROOT_ITEM_ID = '',
  CRYSTALLIZE_DEFAULT_VAT_ID = '',
  CRYSTALLIZE_LANGUAGE_CODE = 'en',
  PUBLISH_INACTIVE_CATEGORIES = true
} = process.env

export {
  CRYSTALLIZE_API_URL,
  MAGENTO_CONSUMER_KEY,
  MAGENTO_CONSUMER_SECRET,
  MAGENTO_ACCESS_TOKEN,
  MAGENTO_TOKEN_SECRET,
  MAGENTO_API_URL,
  MY_CRYSTALLIZE_SECRET_TOKEN_ID,
  MY_CRYSTALLIZE_SECRET_TOKEN,
  CRYSTALLIZE_TENANT_ID,
  CRYSTALLIZE_PRODUCT_SHAPE_ID,
  CRYSTALLIZE_FOLDER_SHAPE_ID,
  CRYSTALLIZE_ROOT_ITEM_ID,
  CRYSTALLIZE_DEFAULT_VAT_ID,
  CRYSTALLIZE_LANGUAGE_CODE,
  PUBLISH_INACTIVE_CATEGORIES
}
