name: Crystallize CLI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: 🏗️ Build and Test
    runs-on: ubuntu-latest
    steps:
        - name: ⬇️ Checkout repo
          uses: actions/checkout@v6
          with:
              fetch-depth: 0
              fetch-tags: false

        - name: ⎔ Setup bun
          uses: oven-sh/setup-bun@v2

        - name: 📥 Download deps
          working-directory: components/cli
          run: bun install --frozen-lockfile

        - name: 🔍 Valid commit message
          working-directory: components/cli
          if: ${{ github.event_name == 'pull_request' }}
          run: bun commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

        - name: 💄 Code Format
          working-directory: components/cli
          run: bun oxfmt --check .

        - name: 📲 Test the builds
          working-directory: components/cli
          run: make build

        - name: 🚀 Sync it!
          env:
              MARKDOWN_TO_CRYSTALLIZE_SHARED_KEY: ${{ secrets.MARKDOWN_TO_CRYSTALLIZE_SHARED_KEY }}
          run: bun apps/doc-2-crystallize.ts components/cli/README.md



